### ISSUE TITLE
mantlepiece

### ISSUE THREAD

**Issue by thewchan** [robinwhittleton/e-w-hornung_a-thief-in-the-night#5]
Ch3 ln 47
mantlepiece -> mantelpiece  (this seems to be a misspelling)

**Comment by robinwhittleton** [comment]
[Low-level enough alternate spelling](https://books.google.com/ngrams/graph?content=mantlepiece%2Cmantelpiece&year_start=1800&year_end=2019&corpus=26&smoothing=3) that I’m happy to correct this.

Fixed in https://github.com/robinwhittleton/e-w-hornung_a-thief-in-the-night/commit/06314b157ca5eb2b41b4ec03f4150b8e2f936773.
